### ISSUE TITLE
Nightly mode is too dark

### ISSUE THREAD

**Issue by jplatte** [ralfbiedert/cheats.rs#101]
If you look at how other sites or apps implement dark / nightly mode, you will almost never find full black backgrounds (except in "OLED dark" themes bc. OLED screens can just completely turn off pixels that are showing full black). 

When toggling the dark mode on cheat.rs the background immediately caught my eye as uncommonly dark. Would you consider switching to a dark grey instead?

See also [Never use Black](https://ianstormtaylor.com/design-tip-never-use-black/).

**Comment by ralfbiedert** [comment]
Thanks for the report and the link! I updated some colors and hope things are better now. Please let me know if you think the balancing is still off.

**Comment by jplatte** [comment]
That was fast! Thanks :)

**Comment by jplatte** [comment]
And as always when I talk about design, I can't resist also recommending [7 Rules for Creating Gorgeous UI](https://learnui.design/blog/7-rules-for-creating-gorgeous-ui-part-1.html) :sweat_smile:

**Comment by ralfbiedert** [comment]
> That was fast! Thanks :)

I needed a creative break from debugging anyway :)

> And as always when I talk about design, I can't resist also recommending 7 Rules for Creating Gorgeous UI 😅

Thanks I'll have a look! Was that a general FYI, of would you say the site does something wrong mentioned in there you think that could be improved?

**Comment by jplatte** [comment]
Just a general FYI :)
