### ISSUE TITLE
Missing slice diagram

### ISSUE THREAD

**Issue by pickfire** [ralfbiedert/cheats.rs#113]
We were explaining slice to a beginner in Rust 众 telegram and found that slice diagram were missing. It should be beside Vec and Box explaination.

**Comment by ralfbiedert** [comment]
I'm a bit confused. Shouldn't this cover slices (under "References & Pointers")?

![image](https://user-images.githubusercontent.com/301288/98537123-139f4100-2289-11eb-8171-1670c897fe6a.png)

The reason it's not near `Vec` is because those types use heap storage.

**Comment by ralfbiedert** [comment]
Ok, I realized the visualizations were actually not that clear around slices, and I assume you meant the difference between true slices `[T]` and slice references `&[T]`. 

I pushed an update, please let me know if you think this clarifies things.
