### ISSUE TITLE
Weaknesses: embedded

### ISSUE THREAD

**Issue by avindra** [ralfbiedert/cheats.rs#114]
Is it accurate? As someone who is just starting to look into Rust, I wonder about this myself and found a conflict:

This was added as a weakness on June 7.

https://github.com/ralfbiedert/cheats.rs/commit/ab76da5b2659ffc5d23fe25c0e11447edf65ea42#diff-200abda264c3530e9cdb5d895e25d50bc3ed567079b39fe2ee3c1d1b5d661e09R170

This seems contrary to Rust, which has a full page on the benefits of using Rust in embedded settings:

https://www.rust-lang.org/what/embedded

**Comment by ralfbiedert** [comment]
Thanks for the report.  Our site currently reads:

> Points you might run into:
> - missing Rust-native libs in some domains, target platforms (esp. embedded), IDE features

The page you link mentions as embedded strengths:
> - Powerful static analysis 
> - Flexible memory 
> - Fearless concurrency 
> - Interoperability
> - Portability
> - Community driven

I don't think there is a conflict. If Rust runs on your device you get all these benefits. 

Unfortunately, Rust only runs on a "relatively small" subset of all possible hardware. Platforms with no or only very limited Rust support, but good C support include:

- most gaming consoles
- GPUs
- most hardware outside the 32-64 bit range
