### ISSUE TITLE
Section about doctests should include `no_run` and other such keywords

### ISSUE THREAD

**Issue by vi** [ralfbiedert/cheats.rs#119]
In [the "Documentation" section](https://cheats.rs/#documentation) I would like to see the list of special things that can be put after comma after ```:

* `no_run`
* `should_panic`
* `compile_fail`
* `ignore`
* (did I miss anything, i.e. `allow_fail` or `edition2018`?)

It is not convenient to look for those things in the [usual documentation page](https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes).

**Comment by ralfbiedert** [comment]
Great idea. I've added something in that section. Might have to move to its own section later if it gets too crowded. 

Note to self, maybe merge with `#[attributes]` section #89 at some point if we ever do that.
