### ISSUE TITLE
Explain non_exhaustive

### ISSUE THREAD

**Issue by sanxiyn** [ralfbiedert/cheats.rs#125]
First, this is a wonderful resource. Thank you so much.

Looking at [API Stability](https://cheats.rs/#api-stability), "Adding new variants" is definitely breaking. It is, but then what is the solution? Often [The non_exhaustive attribute](https://doc.rust-lang.org/stable/reference/attributes/type_system.html#the-non_exhaustive-attribute) is the right solution.

Since the reference is (deliberately) written without any historical information, here are some: [RFC 2008](https://rust-lang.github.io/rfcs/2008-non-exhaustive.html) and [Announcing Rust 1.40.0](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html).

Thanks!

**Comment by ralfbiedert** [comment]
Thanks for the links, clarifying that sounds good.
