### ISSUE TITLE
Explain RFC superscript links

### ISSUE THREAD

**Issue by sanxiyn** [ralfbiedert/cheats.rs#126]
The introductory remark explains BK, EX, STD, NOM, REF, but not RFC.

**Comment by ralfbiedert** [comment]
I wanted to add that earlier, but I also liked the header being only 2 lines. There are a few more labels / emojis not mentioned but I hoped people would infer these. 

Were you confused what `RFC` meant when you encountered it on the page, or do you think someone else may get confused?

**Comment by sanxiyn** [comment]
I was not confused. I thought it may be an oversight, but if it's intentional, no problem!

**Comment by ralfbiedert** [comment]
Ok, I'm closing this for now. In the future having a better "legend" might be good.

**Comment by ralfbiedert** [comment]
Fixed in latest commit a1634bb73bf9fc4bd5fe58d97511ac85367117e7
