### ISSUE TITLE
Update match section: slices, open range, or-patterns

### ISSUE THREAD

**Issue by singalen** [ralfbiedert/cheats.rs#146]
I see a few things missing from the "match" section

* Slice patterns: https://adventures.michaelfbryan.com/posts/daily/slice-patterns/
* Open range patterns: https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#open-range-patterns-added
* Or-patterns: https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#or-patterns

Probably there are others as well (I'm a beginner, so probably don't even know them all).
Thank you!

**Comment by ralfbiedert** [comment]
Thanks for the report. Yes, some patterns might be missing. I'm a bit busy right now, might do that later-later; but will accept PRs in meantime.

**Comment by ralfbiedert** [comment]
I added range patterns and clarified or patterns; but I'm not sure what slice patterns are missing.

**Comment by singalen** [comment]
My bad, I was not specific enough. What is missing from slice patterns is: a) ability to match slices in square brackets; b) the `@` syntax. For example:
```
if let [first, middle @ .., last] = words.as_slice() { ...
```
