### ISSUE TITLE
cheats.rs down

### ISSUE THREAD

**Issue by debuti** [ralfbiedert/cheats.rs#152]
The page seems to be down, I already checked with an online tool and is down for everybody not just me

It's been like this since yesterday at least

**Comment by ralfbiedert** [comment]
Thanks for the ticket. Yes, site is unfortunately down rn. It just so happened that the day after I startled  testing  self hosting somebody thought its a good idea to cut the fiber in my region. Eta from my ISP was 36 hours or so, might be fixed tonight. Cloud flare should still serve backup if you wait a bit (10s). Sorry for inconvenience.
