### ISSUE TITLE
Translate to Korean

### ISSUE THREAD

**Issue by utilForever** [ralfbiedert/cheats.rs#154]
Hello, thank you for sharing awesome content.
I want to translate it into Korean so that Rust users in Korea can access it more easily.
Is it okay if I create a new repository and work on it? The license will be marked.

**Comment by ralfbiedert** [comment]
Thanks for asking! 

> Is it okay if I create a new repository and work on it? The license will be marked.

Yes, translations are totally fine. Feel free to ask if anything is unclear.
