### ISSUE TITLE
pdf has no page number

### ISSUE THREAD

**Issue by time4Wiley** [ralfbiedert/cheats.rs#155]
[rust_cheat_sheet-numbered.pdf](https://github.com/ralfbiedert/cheats.rs/files/7996822/rust_cheat_sheet-numbered.pdf)

Attached a numbered one by manually uploading to service from https://smallpdf.com/add-page-numbers-to-pdf

**Comment by time4Wiley** [comment]
Would be great if the cached one can have page number.

**Comment by ralfbiedert** [comment]
There is probably a setting in the generation script somewhere, PRs welcome.

**Comment by time4Wiley** [comment]
in `.github/workflows/generate_release.yml`, it references the following code:

`./generate_pdf.sh cheats.rs/rust_cheat_sheet.pdf`

Needs to look into `generate_pdf.sh`

**Comment by ralfbiedert** [comment]
Seems to work now.
