### ISSUE TITLE
Add special `$crate` macro token

### ISSUE THREAD

**Issue by mmastrac** [ralfbiedert/cheats.rs#16]
"Rust does not (yet) have a hygiene system for crate references, but it does provide a simple workaround for this problem. Within a macro imported from a crate named foo, the special macro variable $crate will expand to ::foo. By contrast, when a macro is defined and then used in the same crate, $crate will expand to nothing. This means we can write..."

https://doc.rust-lang.org/1.7.0/book/macros.html

**Comment by ralfbiedert** [comment]
Thanks! For some reason it's really hard to find any recent documentation on that one ...
