### ISSUE TITLE
Syntax Highlighting not longer working on the LightMode version of the page

### ISSUE THREAD

**Issue by AlNotAlbert** [ralfbiedert/cheats.rs#161]
https://user-images.githubusercontent.com/87888006/168411166-5006bdd9-adf6-4bde-b675-88b1f0a7c20d.mp4

**Comment by ralfbiedert** [comment]
Thanks for the report. I can't reproduce this here, could you try with another browser? 

Also, what browser does this happen in and what add-ons are active? 

I've seen similar behavior when scripts were blocked, but then both dark and light mode have no syntax highlight.

**Comment by ralfbiedert** [comment]
Ah, what I just noticed, all your boxes are expanded which is weird. This only happens in print mode. 

Can you delete local storage for the site and try again?

**Comment by AlNotAlbert** [comment]
I am on brave browser V1.38.115 Chromium to 101.0.4951.64 osx monterey 12.3.1

it seems deleting my cookies has made it look normal again 😇 😅
