### ISSUE TITLE
Futures

### ISSUE THREAD

**Issue by jmlMetaswitch** [ralfbiedert/cheats.rs#17]
Very useful. Thank you.

Could you perhaps include https://rufflewind.com/img/rust-futures-cheatsheet.html or the equivalent?

The same for Option/Result would be very useful too.

**Comment by ralfbiedert** [comment]
Thanks! Do you think this should be linked, or would you rather see this cheat sheet contain similar information? 

If included here, it would probably be much more condensed though (e.g., short table with most common operations). Also, when including Options / Results the question is where to draw the line to std docs. 

I'm definitely not opposed to it, just trying to figure out the overarching concept.

**Comment by jmlMetaswitch** [comment]
Linked would be fine. One of those nice boxes at the bottom of your page? I don't think it should be condensed.

Are you thinking of having more than one page on your site? If so, perhaps this would be a good one to import into your project, if the author is happy about that.

**Comment by ralfbiedert** [comment]
I'll try to add it in a box and see how it looks (had to yank a few other links because their previews were not "descriptive" enough). If that doesn't work I'll try to address it in the scope of #18.
