### ISSUE TITLE
Unexplained acronym "s.f."

### ISSUE THREAD

**Issue by ancorehraq** [ralfbiedert/cheats.rs#174]
>async { return } Inside async a return only [REF](https://doc.rust-lang.org/stable/reference/expressions/block-expr.html#control-flow-operators) 🛑 exits that {} block, i.e., async {} is s.f.!

What is s.f.?

**Comment by ralfbiedert** [comment]
"Surrounding function". It refers to the previous line, but yes this could be reworded.
