### ISSUE TITLE
"Implementing Families — impl<>" compilation error

### ISSUE THREAD

**Issue by scturtle** [ralfbiedert/cheats.rs#175]
The code in `Working with Types` -> `Types, Traits, Generics` -> `Generics` -> `Implementing Families — impl<>`:
```rust
use core::fmt::Display;

trait S<T> {
    fn foo(&self, x: T);
}

impl<T> S<T> where T: Copy + Display {
    fn foo(&self, x: T) {}
}

fn main() {}
```

causing a compilation error:
```rust
error[E0782]: trait objects must include the `dyn` keyword
 --> src/main.rs:7:9
  |
7 | impl<T> S<T> where T: Copy + Display {
  |         ^^^^
  |
help: add `dyn` keyword before this trait
  |
7 | impl<T> dyn S<T> where T: Copy + Display {
  |         +++

For more information about this error, try `rustc --explain E0782`.
```

It seems that a `dyn` should be added. Any more references about this feature?

**Comment by ralfbiedert** [comment]
Sorry for the confusion, `S<T>` is meant to be a type, not a trait. This works:

```rust
use core::fmt::Display;

struct S<T>(T);

impl<T> S<T> where T: Copy + Display {
    fn foo(&self, x: T) {}
}

fn main() {}

```

**Comment by ralfbiedert** [comment]
About your question, I've also added a link in that section to [Generic Implementations](https://doc.rust-lang.org/stable/reference/items/implementations.html#generic-implementations).
