### ISSUE TITLE
Issues with the PDF

### ISSUE THREAD

**Issue by jonasmalacofilho** [ralfbiedert/cheats.rs#179]
The current PDF (from 76a86d3) has some issues. One of the worst can be seen bellow, but in general many of diagrams are currently badly rendered.

![Screenshot from 2023-02-03 00-43-27](https://user-images.githubusercontent.com/1832496/216507595-f113ed60-fe41-4df4-9345-092fbd0f3faa.png)

**Comment by ralfbiedert** [comment]
Thanks for the report. I just had a quick look and fixed some minor CSS / HTML issues, but unfortunately I don't know what's causing this, the debugging tools for printing are pretty bad. For example, Firefox renders the page perfectly when enabling "Print Media Simulation", but still produces artifacts in the PDF:

![image](https://user-images.githubusercontent.com/301288/216569765-07ef3b57-1506-4823-bc86-6551b3f73f24.png)

I don't have so much time digging deeper right now, but help / PRs to fix this would be very welcome.

**Comment by ralfbiedert** [comment]
Ah, and meanwhile there's a hack you can try to build your own PDF. If you open 

https://cheats.rs/#_print

you get all tables unfolded, which is what our script does internally, and then you can try to print with your favorite browser and see if the result is better. You can of course just print the site as-is, which looks a bit nicer but doesn't unpack tables.

**Comment by jonasmalacofilho** [comment]
Thanks for the reply! And, actually, I mostly use the website... just wanted to let you know of the issue.

But I'll see if I can take a look when I have some time (although, due to some personal issues at the moment,  that might take a while).

Thanks again!

**Comment by ralfbiedert** [comment]
This seems to have fixed itself.
