### ISSUE TITLE
[RFC] Next Steps

### ISSUE THREAD

**Issue by ralfbiedert** [ralfbiedert/cheats.rs#18]
Currently this is primarily a sigils + keywords cheat sheet.

However, cases [like the ones in here](https://www.reddit.com/r/rust/comments/a1846o/rust_quiz_26_medium_to_hard_rust_questions_with/), (esp. [this one](https://www.reddit.com/r/rust/comments/a1846o/rust_quiz_26_medium_to_hard_rust_questions_with/eaop291/)) make me think more surprising syntax combinations should be listed as well (e.g., we are already a bit inconsistent with repeatedly documenting `_`, although I believe this improves clarity). 

Even further, we could include cheats around 

- memory layout / data types (#11)
- common types
- iterator chaining
- lifetimes and borrows
- macros
- futures (#17)

The basic question is, should these be included, or rather linked to? If they are included, the whole cheat sheet will probably transform from a "sigils" and "keywords" layout, to a more functional grouping.

There is also the balance of being comprehensive vs. lightweight. 

I am generally in favor of expanding this, as long as I don't get lost in it as a user.

**Comment by jmlMetaswitch** [comment]
Love this. My take is

- If you think a source is elegant and unlikely to vanish, it's fine to link it
- If the author of an external source is happy, you could import it as-is as a separate page linked from your index article
- If your index article grows much more it would be worth pulling out topics into separate pages, but it's fine at the moment
- It's fine for you to add content in separate articles (or to accept contributions) that aren't as pretty as your index page, and to leave fixing it up as an issue.

**Comment by ralfbiedert** [comment]
> * If you think a source is elegant and unlikely to vanish, it's fine to link it

Yes, fully agree!

> * If your index article grows much more it would be worth pulling out topics into separate pages, but it's fine at the moment

I feel somewhat strongly about keeping everything on a single page as much as possible. One of the biggest pain points leading to this cheat sheet was the inability to search for certain constructs. As weird as it sounds, but `CTRL+F` is doing a much better job than Google in this respect. However, I agree that if topics grow _too_ large, breaking things out might be inevitable.

**Comment by ralfbiedert** [comment]
Alright, based on the feedback so far I am slightly modifying the chat sheet. The sections "Sigils" and "Keywords" will merge and cluster into smaller syntactic sections around:

- Data Structures
- References & Pointers
- Functions & Behavior
- ...

That will allow syntactic variants and combinations to be added more naturally, and gives more room for explanations. 

A (very WIP) version can be found here [cheats.rs/beta](https://cheats.rs/beta/), the tracking branch is [by_group](https://github.com/ralfbiedert/cheats.rs/tree/by_group).

**Comment by ralfbiedert** [comment]
I would argue this is done now. Result looks much more like a traditional cheat sheet.
