### ISSUE TITLE
Blurred font in Safari

### ISSUE THREAD

**Issue by lucioroadtoglory** [ralfbiedert/cheats.rs#180]
I'm the only nerd at the internet using Safari, but the cheatsheet site is blurred for me. I'm using the `Safari - Version 16.3 (18614.4.6.1.5)` as `MacOS Ventura - Version 13.2` but I was tried using `Safari - Version 15.6 (15613.3.9.1.7, 15613)` running in `macOS Catalina - Version 10.15.7`. But this problem is fixed running in another browser (I tried Mozilla Firefox and Chromium), but only Safari keeps blurred. Can someone give-me more pixels? 

Safari example#1
![Screenshot 2023-02-07 at 14 37 26](https://user-images.githubusercontent.com/62335491/217326830-96bda0c8-f4d7-4dbf-af21-b10b4a6b2765.png)

Safari example#2
![Screenshot 2023-02-07 at 14 36 59](https://user-images.githubusercontent.com/62335491/217326858-88a05a60-34c1-4035-a990-00f33b207c98.png)

Chromium example#1 (of 1)
![Screenshot 2023-02-07 at 14 48 53](https://user-images.githubusercontent.com/62335491/217327484-219e0171-f120-425a-984d-adf0da621ddc.png)

I don't know how fix this because it's Zola project and I'm React developer (⚛️) so I cannot do pull request (💀) but it's problably a Safari problem to caching font to optimize font loading (maybe).

**Comment by ralfbiedert** [comment]
For me even your window decoration is blurred in these screenshots :) 

Since every other browser seems to work fine I think this is a Safari issue, but could you try 

- (un)setting `transform` to `scale(1.0)` in `body > div.page > div.page__content > div.book-content` (see screenshot below)
- resizing the window so that the two columns barely fit on the screen?

![image](https://user-images.githubusercontent.com/301288/217336446-d928e1e6-ef29-4c07-aa2d-0769affc9653.png)

**Comment by lucioroadtoglory** [comment]
If I open "Inspect Element" works fine (because reduce the app width):
![Screenshot 2023-02-07 at 15 52 36](https://user-images.githubusercontent.com/62335491/217338985-c6875d93-e48d-4087-842c-f2ab2dcc3fad.png)

And removing transform-scale works fine too:
![Screenshot 2023-02-07 at 15 52 44](https://user-images.githubusercontent.com/62335491/217338987-9be62a0c-0f55-4fb2-b879-2efe757b3c87.png)

**Comment by ralfbiedert** [comment]
Not sure what to do, this seems to be a Safari font rendering bug w.r.t. `scale`. For now my recommendation would be ~~not to hold it like that~~ to resize the window. I'm a bit reluctant adding a workaround, as they tend to be brittle and I don't have Safari device to test anymore.

Any other ideas?

**Comment by lucioroadtoglory** [comment]
The `zoom` css property looks good to solve this problem in Safari, replacing the `transform/scale` property
![image](https://user-images.githubusercontent.com/62335491/217353920-4cb0e1ed-cf9c-436f-ba3e-d3a8fe45e90c.png)

I tested in Safari and Chromium but I don't know the behavior in Mozilla Firefox 🔥
![Screenshot 2023-02-07 at 17 31 12](https://user-images.githubusercontent.com/62335491/217358309-c93f7c56-a0ec-40ed-a6e9-3c462f50be33.png)

**Comment by ralfbiedert** [comment]
Apparently this doesn't work in  Firefox :(

https://caniuse.com/css-zoom

**Comment by lucioroadtoglory** [comment]
Can we use this?
```css
.book-content {
    -moz-transform: scale(1.05); /* property for Firefox */
    zoom: 105%; /* property others browsers */
}
```

because using this:
```css
.book-content {
    transform: scale(1.05);
    zoom: 105%; 
}
```
can duplicate the scale in the app.

**Comment by lucioroadtoglory** [comment]
I don't have this issue using Safari in iOS
![image](https://user-images.githubusercontent.com/62335491/218154943-460c1f4c-ba35-4b36-937c-ed1b663a0e3e.png)

**Comment by ralfbiedert** [comment]
Let's try this. Might have to revert if it breaks rendering in other browsers.

**Comment by ralfbiedert** [comment]
Ah, just noticed I have some trouble deploying as I'm on vacation. ETA might be a few days.
