### ISSUE TITLE
error: the `?` macro repetition operator does not take a separator

### ISSUE THREAD

**Issue by guilliamxavier** [ralfbiedert/cheats.rs#183]
The "**Macros &amp; Attributes**" section contains these three rows:

| | |
| --- | --- |
| `$(x),*` | Macro **repetition** [<sup>REF</sup>](https://doc.rust-lang.org/stable/reference/macros-by-example.html#repetitions) _zero or more times_. |
| &nbsp;&nbsp;&nbsp;&nbsp; `$(x),?` | Same, but _zero or one time_. |
| &nbsp;&nbsp;&nbsp;&nbsp; `$(x),+` | Same, but _one or more times_. |

but the linked reference adds:

> Since `?` represents at most one occurrence, it cannot be used with a separator.

and indeed, trying to compile the following:

```rust
macro_rules! m {
    ($(x),*) => { $(x),* };
    ($(x),?) => { $(x),? };
    ($(x),+) => { $(x),+ };
}
```

gives an error (title of this issue) on the second arm (twice: for the pattern and for the expansion).

PS: Thanks for the work!

**Comment by ralfbiedert** [comment]
Hah, thanks!
