### ISSUE TITLE
Date stamp is wrong ? 

### ISSUE THREAD

**Issue by tjyang** [ralfbiedert/cheats.rs#191]
Is dot character after "15" extra ?  
- This format of Day Month looks weird to me. Please close it if this is intended.

![image](https://github.com/ralfbiedert/cheats.rs/assets/378638/25391a2b-1900-4899-b4bb-3987fed95eb3)

**Comment by ralfbiedert** [comment]
It's the German date format. The `.` there sort of stands for _th of_ (as in '15 _-th of-_ January). We had the US date format before which was also confusing for some (#138). I don't think there is a "bug free" solution to that ...
