### ISSUE TITLE
Add section on `format!` flags?

### ISSUE THREAD

**Issue by dchenbecker** [ralfbiedert/cheats.rs#29]
I don't see a section on format flags (e.g. debug print, justification, field width, and other specifiers). I would be happy to PR a new section for this.

**Comment by ralfbiedert** [comment]
Sounds interesting. What do you think should be included, and what would the relationship be towards the [std::fmt](https://doc.rust-lang.org/std/fmt/) guide?

**Comment by dchenbecker** [comment]
The module documentation is excellent, but it's roughly 11 printed pages, definitely not what I would consider a "cheat sheet". I was thinking a simple table highlighting common use cases (e.g. width, alternate forms, positional and named params), with a link to the module docs. As a rough example of what this section would look like:


### <a name="formatting_strings"></a> Formatting Strings

There are a variety of additional flags that you can specify when using one of the following macros to perform string formatting:

* [`format!(<format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.format.html) - Creates a String using interpolation of runtime expressions.
* [`eprint!(<format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.eprint.html) - Prints to the standard error.
* [`eprintln!(<format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.eprintln.html) - Prints to the standard error, with a newline.
* [`print!(<format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.print.html) - Prints to the standard output.
* [`println!(<format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.println.html) - Prints to the standard output, with a newline.
* [`write!(<stream>, <format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.write.html) - Write formatted data into a buffer.
* [`writeln!(<stream>, <format string>, [<parameter> ...])`](https://doc.rust-lang.org/std/macro.writeln.html) - Write formatted data into a buffer, with a newline appended.

The full grammar is [specified in the `std::fmt`](https://doc.rust-lang.org/std/fmt/index.html#syntax) documentation.

<div class="cheats">

There are three ways to select which argument you want to format:

| Example | Explanation |
|---------|-------------|
| `{}` | Formats the "next argument" in this position. Multiple instances can be used for multiple arguments |
| `{N}` | Where N is a number ≥ 0, formats the Nth argument (starting at zero) in this position. Note that the referenced position of `{}` is independent from any explicitly positioned arguments |
| `{<name>}` | Used with `<name> = <value>` arguments, which must come after any positional arguments. |

Flags are specified with a `:<flags>` suffix inside the brackets:

| Example | Explanation |
|---------|-------------|
| `{:>15?}` | Right-align the next positional argument with width of 15, using [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) |
| `{2:#?}` | Pretty-print the 3rd argument using [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) |
| `{1:<20}` | Left-align the 2nd argument with a width of 20 |
| `{myVal:^2$}` | Center ("^") the "myVal" named argument with a width specified by the 3rd argument |
| `{:>.3}` | Format with precision of 3. Note that precision for non-numeric values indicates maximum (truncated) width |
| `{:.N$}` | Format with precision specified by the Nth argument (must be an integral value) |
| `{:.*}` | Format with precision specified by the integral argument *preceding* the argument to be formatted |
| `{myVal:#x}` | Format the `myVal` named argument using hexadecimal, with a leading `0x` (from the `#` "alternative format" flag) |

</div>

**Comment by ralfbiedert** [comment]
I think cheats on the "most common use cases" would make sense. 

My main hesitation is that there might be a number of areas where similar cheats could be added, which wouldn't really make this a _language_ cheat sheet anymore. On the other hand, _Tooling_ already broke that rule.

Let's add it, but the implication might be that at some point the whole thing would have to be reorganized if it gets too big.

**Comment by dchenbecker** [comment]
I worked to condense down to common cases as part of the PR. I haven't convinced myself that the examples section is needed.

**Comment by ralfbiedert** [comment]
Closing since #30 merged.
