### ISSUE TITLE
examples for macro captures

### ISSUE THREAD

**Issue by Luro02** [ralfbiedert/cheats.rs#34]
I think it's very hard for new people to figure out what kind of captures should be used for certain types of code.

For example is this a pattern?:
```rust
match value {
    1 => 2
}
```
or
```rust
1 => 2
```
or
```rust
{
   1 => 2
}
```

Therefore the `Explanation` should include a bit more than just 

"`$x:pat` is a pattern. (I guess that's obvious from the name itself)"

**Comment by ralfbiedert** [comment]
I agree the `Macro Capture` section is a bit meager. What explanation would you suggest?

**Comment by Luro02** [comment]
| Macro Capture  | Explanation |
|---|---|
| `$x:item` | An item, like a function, struct, module, etc. | 
| `$x:block` | A block of statements (`{ let value = 0; let value_1 = 1; }`) and/or an expression, surrounded by braces (`{ let value = 0; }`). | 
| `$x:stmt` | A statement, like `let value = 0;`, `String::new();` or `vec![];` |
|  | A pattern, for example: `Some(t)`, `(17, 'a')` or `_`. |
| `$x:expr` | An expression like `value`, `1 + 1`, `String::new()` or `vec![]` |
| `$x:ty` | A type like `String`, `usize` or `Vec<u8>` |
| `$x:ident` | An identifier is the variable name, for example in `let value = 0;` the identifier is `value` |
| `$x:path` | A path (e.g. `foo`, `::std::mem::replace, transmute::<_, int>`, …). |
| `$x:meta` | A meta item; the things that go inside `#[...]` and `#![...]` attributes. |
| `$x:tt` | A single token tree. (See [here](https://stackoverflow.com/a/40303308) for an explanation)
