### ISSUE TITLE
add $(,)* or $(,)? to the cheat sheet

### ISSUE THREAD

**Issue by Luro02** [ralfbiedert/cheats.rs#35]
Some people prefer to have trailing commas, but macros don't allow this by default

```rust
macro_rules! vec {
    ( $( $x:expr ),* ) => {
        {
            let mut temp_vec = Vec::new();
            $(
                temp_vec.push($x);
            )*
            temp_vec
        }
    };
}

vec![ 1, 2, 3, ];
```
will give a compiler error.

You can fix this by adding `$(,)*` to the end of the capture like this:
```rust
macro_rules! vec {
    ( $( $x:expr ),*  $(,)*) => {
        {
            let mut temp_vec = Vec::new();
            $(
                temp_vec.push($x);
            )*
            temp_vec
        }
    };
}

vec![ 1, 2, 3, ];
```
I got this from https://stackoverflow.com/a/43143459

**Comment by ralfbiedert** [comment]
I'm not sure about this one. Although I agree it's interesting, I have the feeling this is a bit too "special". Is that capture widely used, or a surprising for of syntax over `$(x),*` that it should be mentioned separately?

**Comment by Luro02** [comment]
nevermind
