### ISSUE TITLE
Pdf request

### ISSUE THREAD

**Issue by cata0309** [ralfbiedert/cheats.rs#38]
Hey !
Is there any way to make the site available in PDF version with all the functionalities. I am working offline most of the time from some time.

**Comment by TomasHubelbauer** [comment]
There is a link at the very bottom to print a PDF or download a cached one.

**Comment by ralfbiedert** [comment]
Hey, yes. Preferably you should click **Generate PDF** since the pregenerated one outdates very quickly.  

I'm closing this unless there is something missing about the PDF generation, in that case feel free to comment.
