### ISSUE TITLE
Considering using online hosted fonts especially Fira Code for your website

### ISSUE THREAD

**Issue by cata0309** [ralfbiedert/cheats.rs#39]
That would make the website much more cleaner and not rely on users fonts.

**Comment by ralfbiedert** [comment]
I'm generally open to using Fira Code, as I'm using this myself with ligatures. Some concerns and comments though:

- If I switch font, I'd also like to self-host the font to get rid of the Google hosted fonts entirely for privacy reasons 
- Using Fira Code + ligatures might make it harder to read for some users not used to it
- I'd need some help with reliably embedding custom fonts as I've never done that cross-platform. 

Any suggestions or experiments are welcome.

**Comment by cata0309** [comment]
Hello, I will help you in any way I can as I do love Rust language a lot!
I will take some of the issues you discovered and try my best to solve them:

``Using Fira Code + ligatures might make it harder to read for some users not used to it``
Fira Code can be tweaked without having to deal with custom builds and waste a lot of time with that.
I don't know about the **TTF**(True Type Fonts) versions of text fonts but I do know that **OTF** fonts versions offer some very useful features( I stopped using **TTF** when I switched to Linux as I prefer **OTF** (Open Type Fonts) quality on my distribution of Linux ).
You can easily turn off ligatures, change the calt or change the type of zero( slashed or dotted ) with some easy properties. I used them in my text editor, Atom, I do find ligatures useful but I had to learn for exams in the past and I couldn't afford to write on the CS exams ligatures.
I used this code in **LESS** (Leaner Style Sheets) to disable ligatures, cald and change the zero style (ON/OFF -> OFF means dotted and ON means slashed )
` -webkit-font-feature-settings: "liga" off, "calt" off,"zero" off;` 
You can find more information on https://sparanoid.com/lab/opentype-features/

``If I switch font, I'd also like to self-host the font to get rid of the Google hosted fonts entirely for privacy reasons``
I will make some research about this, as the time of writing I know about an article that talks about this:
https://www.webdesignerdepot.com/2014/03/the-best-way-to-serve-fonts-to-your-website/

**Comment by ralfbiedert** [comment]
Thanks for the links. 

I think the MVP would be to create a branch that shows Fira Code self-hosted (via `zola serve`), so it can be tested on a couple of devices / browsers. 

If that looks good that can be put live, maybe with an option to toggle ligatures (next to the one to toggle Night Mode).

**Comment by cata0309** [comment]
Sounds awesome !

**Comment by ralfbiedert** [comment]
Quickly hacked something by replacing the Google font import and some minor tweaks:

https://github.com/ralfbiedert/cheats.rs/tree/fira_code

**Comment by ralfbiedert** [comment]
Current version:

![old](https://user-images.githubusercontent.com/301288/62571084-c4ea4680-b890-11e9-873a-e311bb7751b9.png)

Fira Code (example, w. ligatures):
![new](https://user-images.githubusercontent.com/301288/62571094-cb78be00-b890-11e9-88b8-8f6e91968d39.png)

**Comment by cata0309** [comment]
Looks awesome if you ask me, both of them, much more cleaner. I will test the version with the Fira Code font tomorrow as I have to install Zola and I had a hard time finding it for my Linux distro( the binary offered by them can't compile or build the site and I am sure I need to do a little more research on how to setup it )

**Comment by ralfbiedert** [comment]
Some testing w. testing & ligature toggling:

| Browser| Result |
| ------------- | ------------- |
| Firefox 68, Windows | Works fine. |
| Chrome 76, Windows | Works fine. |
| Edge 44.18362, Windows | Always shows ligatures, can't toggle off.  |
| Safari, iPhone, iOS 12.3.1 | Doesn't show ligatures, can't toggle on. |
| Safari, iPad, iOS 12.3.1 | Doesn't show ligatures, can't toggle on.  |

**Comment by cata0309** [comment]
Linux : Chrome and Firefox work as expected, with and without ligatures

**Comment by cata0309** [comment]
Consider making the font bigger with at least 1 px, code sections look kinda small on PC

**Comment by cata0309** [comment]
Fira Code Retina size 14 px ligatures:
![image](https://user-images.githubusercontent.com/35623921/62611893-205b1980-b90f-11e9-9680-5559bca7b79c.png)


Iosevka Medium size 14 px ligatures:
![image](https://user-images.githubusercontent.com/35623921/62612134-8a73be80-b90f-11e9-87ec-19d4af984ee0.png)

**Comment by ralfbiedert** [comment]
> You should test Retina version of the font  

Interesting, how can I enable this? I'm not finding much info on the Fira Code web site, although I found a few sites mentioning it.

> Consider making the font bigger with at least 1 px, 

I can try to go 0.5px larger, but right now it's almost at the limit before lines start to wrap, which would mean re-wording lots of things. 

> Iosevka Medium 

Looks much worse than Fira Code in my opinion.

**Comment by cata0309** [comment]
I understand, the thing about about Iosevka that makes it look bad on websites because it is narrow
I close the issue since the website supports Fira Code font
