### ISSUE TITLE
Slices can sometimes live on the stack

### ISSUE THREAD

**Issue by gnzlbg** [ralfbiedert/cheats.rs#43]
RFC1909 (https://github.com/rust-lang/rust/issues/48055) was merged and is partially implemented on nightly, which means that this

```rust
#![feature(unsized_locals)]
fn foo(x: [u8]) { dbg!(&x) }
```

works and will land on stable at some point. 

Currently, the cheat-sheet says:

> Array type of unspecified length, i.e., slice. STD EX REF Can't live on stack 

I think it would be good to add a foot note or super script after "Can't live on stack" saying "for now", and linking to that tracking issue.

**Comment by ralfbiedert** [comment]
Didn't know that, thanks!
