### ISSUE TITLE
"Tooling" needs `cargo new` command

### ISSUE THREAD

**Issue by Mr-Andersen** [ralfbiedert/cheats.rs#50]

**Comment by ralfbiedert** [comment]
Interesting. Up until now I didn't even know that `new` existed. After glossing over the docs, I'm still a bit confused ... isn't `cargo init` effectively 'more powerful' than `cargo new`, since `init` can run in the current or a given directory, while `new` always requires a path?

**Comment by Mr-Andersen** [comment]
Well, yes, we can say that it's more flexible, but it's simpler. I always use `new`

**Comment by ralfbiedert** [comment]
Hm, I'm still not sure if I find it simpler:

- In an empty directory I can type `cargo init` and it will create a new project in that directory. However, `cargo new` will fail.
- In any case, I can type `cargo init x` or `cargo new x`, and it will create a project named `x` in the respective `x/` directory.

Am I missing something?

**Comment by Mr-Andersen** [comment]
How do you create rust project? I go to `Work` dir and do `cargo new my_project && cd my_peoject`

**Comment by ralfbiedert** [comment]
`cargo init my_project && cd my_project` :)

**Comment by Mr-Andersen** [comment]
Lol. I just made diff of `cargo init -h` and `cargo new -h` and all the differences are name of subcommand and that `new` uses `.` as default path for new project.

**Comment by ralfbiedert** [comment]
Would you then agree that `cargo init` is sufficient, or do you see another aspect why `new` should also be listed?

**Comment by Mr-Andersen** [comment]
Yes, I agree. Let's close this issue
