### ISSUE TITLE
"Hardcoded magic"

### ISSUE THREAD

**Issue by ralfbiedert** [ralfbiedert/cheats.rs#51]
From Reddit:

> Next to the “invisible sugar” perhaps also provide ”hardcoded magic” for traits and other stuff that “seems” like a normal library item, but cannot be reimplemented by the user in terms of other items. For example, the traits “Copy”, “Clone”, “Deref”, etc.

**Comment by cata0309** [comment]
You should clarify what those terms mean !! It could be anything, different people, different "hardcoded magic".

**Comment by ralfbiedert** [comment]
I'm not sure myself yet, this was someone's comment from Reddit, just pasted as-is. I filed it because I was generally open to the idea but didn't really know how to execute. Feedback welcome!

**Comment by cata0309** [comment]
I will help you when I will master such magic, such power :))

**Comment by ralfbiedert** [comment]
More generally it's some of / all the things the compiler has built-in magic, that a regular user couldn't do. Prime example `UnsafeCell`, which could not be implemented by anyone else.

**Comment by cata0309** [comment]
I will look at it in the future, thank you for the information

**Comment by ralfbiedert** [comment]
Alright. After I've given this some thought I'm not sure this is really useful in daily coding, or more of a curio. 

When writing `unsafe` understanding the special nature of `UnsafeCell` probably makes lots of sense (although that should probably be part of an "Unsafe 101"), but as a developer I pretty much would expect all the marker traits to be "special" by default.

Closing for now.
