### ISSUE TITLE
Change let pattern matching example

### ISSUE THREAD

**Issue by robinst** [ralfbiedert/cheats.rs#55]
First up, great cheat sheet! Thanks for creating it, I think it will be very useful for heaps of people :).

While reading, the following example confused me a bit:

    let Some(x) = Some(5);

Because it does not compile:

> refutable pattern in local binding: `None` not covered

Did you mean for `Some` to be the `Option` variant or a placeholder for some type? Maybe you could change it to a tuple struct instead, e.g. `let S(x) = value`?

**Comment by ralfbiedert** [comment]
Ah, thanks. Yes, I mixed this up.
