### ISSUE TITLE
extern "C" fn

### ISSUE THREAD

**Issue by jethrogb** [ralfbiedert/cheats.rs#59]
`extern "C" fn` is currently listed as “External dependency for FFI”. I don't think that's correct. That is what `extern "C" { ... }` is. `extern "C" fn` just specifies the calling convention.

**Comment by ralfbiedert** [comment]
Isn't `extern "C" {}` the same as `extern "C"` except that the former applies to more than one item?

In any case, I agree the calling convention part could be emphasized. How about:

```
| `extern "C" {}`  | External dependencies and calling convention (e.g., `"C"`) for **FFI**.  |
```

**Comment by jethrogb** [comment]
> Isn't `extern "C" {}` the same as `extern "C"` except that the former applies to more than one item?

No. `extern "C" {}` lets you define a list of external items (static variables, function *declarations*). `extern "C" fn ...` is a function *definition* (with a function body).

**Comment by ralfbiedert** [comment]
TIL; thanks! I updated the site, please reopen / comment if you think it's still wrong.
