### ISSUE TITLE
suggestion: proc macro section

### ISSUE THREAD

**Issue by yaahc** [ralfbiedert/cheats.rs#61]
I can't seem to find any information about proc macros in cheats.rs. I feel like this is a relatively important part of the rust ecosystem and it deserves a section. Particularly with `syn` and `quote` just hitting their 1.0.0 releases, it seems like a good time to bring in some documentation for them.

I'd be happy to add one myself as a PR but I don't know proc macros well yet so it will have to wait until after I take the time to properly learn them.

**Comment by ralfbiedert** [comment]
I haven't thought about this before, and I'm not generally opposed, but first reaction / questions:

- Isn't this more of a library concern, e.g., "how to use crate {syn, quote, proc_macro}"?
- If yes, where should we generally draw the line for inclusion of libs?
- Regardless of above, could you outline what you would like to see in that section?

Ideally, a section is longer than a few lines, but not longer than about "a page", and conveys the essence in mostly independent one-liners. 

Another thought, that section (I assume it will be a guide?) should then be about macros in general, and include a few lines about "macros by example"?

**Comment by yaahc** [comment]
I feel like the proc macro crates are a central enough where they warrants special attention. `syn` and `quote` don't really have competing crates in the ecosystem (that I know of) and `proc_macro` is distributed with std already.

As for the outline of the section, I don't know yet :/ Like I said I still need to properly learn proc-macros. I'm planning on doing @dtolnay's proc-macro-workshop in the not too distant future and hopefully in the process I'll learn enough about proc macros where I can get a feel for what kind of syntax bits I'd expect to constantly find myself searching for.

**Comment by ralfbiedert** [comment]
> I feel like the proc macro crates are a central enough where they warrants special attention. syn and quote don't really have competing crates in the ecosystem (that I know of) and proc_macro is distributed with std already.

Fair enough. I don't think "being the only crate" (or even std) should warrant it on its own, but I agree that they are central and in a sense re-define the language. 

> hopefully in the process I'll learn enough about proc macros where I can get a feel for what kind of syntax bits I'd expect to constantly find myself searching for.

Yes, that would be great! I have never touched them, but once you know more, if you could post an outline of what cheats should go in would help to discuss!

**Comment by kud1ing** [comment]
Another point of view: i think `cheats.rs` should be deliberately minimal and about Rust the language. More complex stuff that require libraries should got to https://github.com/rust-lang-nursery/rust-cookbook

**Comment by ralfbiedert** [comment]
> I think cheats.rs should be just about Rust the language (at most also about libstd).
> More complex stuff that require libraries should got to https://github.com/rust-lang-nursery/rust-cookbook

I agree, although in this particular case it boils down to how the section is done: 

- If it ended up as a, say, `syn`-centric list of API calls it definitely shouldn't go here. 
- But if it provided actionable insights how ubiquitous constructs like `#[derive]` work and are whipped up (e.g., like the current Async-Await section), that could be language-relevant.

**Comment by ralfbiedert** [comment]
Hi, since the progress here seems to have stalled for a few weeks I'm temporarily closing this issue, as I don't have the knowledge to drive this myself. 

This is purely for "issue hygiene" and doesn't mean I'm opposed to the item. Please re-open / comment if there is any progress!

**Comment by yaahc** [comment]
Will do, I'll save this on my list of issues to maybe do someday, I'll probably have more ideas here once I've properly learned proc-macros myself.
