### ISSUE TITLE
suggestion: section about thread-safety (guide?)

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#63]
* when is something thread-safe?
* https://rust-unofficial.github.io/too-many-lists/third-arc.html
* `std::marker::Send`, `std::marker::Sync`:
  * From https://limpet.net/mbrubeck/2019/02/07/rust-a-unique-perspective.html
    * T: Send means it's safe to access a T on a single other thread, where one thread at a time has exclusive access. A value of this type can be moved to another thread by unique ownership, or borrowed on another thread by unique reference (&mut T). A more descriptive name for this trait might be UniqueThreadSafe.
    * T: Sync means it’s safe for many threads to access a T simultaneously, with each thread having shared access. Values of such types can be accessed on other threads via shared ownership or shared references (&T). A more descriptive name would be SharedThreadSafe.
  * From https://www.reddit.com/r/rust/comments/e66aqb/need_clarification_about_sync_properties/f9o9pra/
    * "Think of Send as: it is safe to give another thread unique access to this value"
    * "Think of Sync as: it is safe to share access to this value across threads."
  * [Examples](https://www.reddit.com/r/rust/comments/ctdkyr/understanding_sendsync/exk8grg/):
    * `Send+Sync`: most types, `AtomicUsize`
    * `!Send+Sync`: `MutexGuard`, `RwLockReadGuard`, `RwLockWriteGuard`
    * `Send+!Sync`: `Cell`, `RefCell`
    * `!Send+!Sync`: `Rc`, `Formatter`, `&dyn Trait`
  * https://doc.rust-lang.org/nomicon/send-and-sync.html
  * https://doc.rust-lang.org/book/ch16-04-extensible-concurrency-sync-and-send.html
* `Mutex<T>`, `RWLock<T>`
* https://doc.rust-lang.org/std/sync/atomic/

**Comment by ralfbiedert** [comment]
I'm generally open to the idea, but I'm still not sure what should go inside. 

- Are you suggesting to document marker traits and synchronization primitives from `std`?  
- Is this about paradigms?
- Is there an additional language aspect?
...

**Comment by kud1ing** [comment]
I've not formed a complete opinion yet. Inspired by https://www.reddit.com/r/rust/comments/ctdkyr/understanding_sendsync/ i've added the trait combinations above, for which examples could be interesting/insightful.

**Comment by ralfbiedert** [comment]
Quick heads up, I started to look into something similar as part of a visual "data structures" section, but ended up fighting some CSS problems on mobile. 

The actual table you referenced might end up in there somehow. 

Will try to continue when I have a bit more time.

**Comment by kud1ing** [comment]
Nice, thank you.
