### ISSUE TITLE
Add guide for writing polymorphic code

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#65]
I think a guide would be nice that explains what to choose when writing polymorphic code (sort of the inverse of https://cheats.rs/#generics-constraints which explains what the syntax means if you see it in the wild).

See also:
* https://stackoverflow.com/questions/32059370/when-is-it-appropriate-to-use-an-associated-type-versus-a-generic-type

# Functions (arguments/return values)

## `dyn Trait`

dynamic binding (trait object) => no monomorphization

* advantages:
  * smaller binaries
* disadvantages:
  * runtime overhead (vtable)
  * the trait must be object-safe:
    * return type must not be `Self`
    * there are no generic type parameters.

## `impl Trait`

static binding => monomorphization

* advantages:
  * no runtime overhead
* disadvantages:
  * larger binaries
  * implies that all return values are of the same type
  * can not be used in traits at return position

## generics

static binding? monomorphization?

* advantages:
* disadvantages:

# Data structures

* enums:
  * static binding (?)
  * advantages:
  * disadvantages:
    * the set of possible values can not be extended externally
* generics with associated types
  * advantages:
    * code using that structure gets simpler
  * disadvantages:
* generics without associated types
  * advantages:
  * disadvantages:

This may or may not fit https://cheats.rs/#generics-constraints

**Comment by ralfbiedert** [comment]
Is that when defining functions?

**Comment by kud1ing** [comment]
Good question. I've updated the text above. I must admit, i don't have a clear picture yet what i think is missing.

**Comment by kud1ing** [comment]
One thing that could be added is that `fn f() -> impl T` implies that all return values are of the same type.

**Comment by ralfbiedert** [comment]
Also closing this one as it seems to have stalled and I'm not quite sure how I would address this. 

This is purely for "issue hygiene" and doesn't mean I'm opposed to the item. Please re-open / comment if there is any progress!
