### ISSUE TITLE
What criteria for 3rd party cargo tools?

### ISSUE THREAD

**Issue by ralfbiedert** [ralfbiedert/cheats.rs#69]
A few 3rd party `cargo xxx` commands have been added, and they seem useful.

However, there are several dozen, if not [hundreds](https://lib.rs/keywords/cargo) cargo helpers out there, and we can't list them all.

What should be the criteria for being listed?

- [ ] Downloads on crates.io > X?
- [ ] Stars on Github > Y?
- [ ] Actively maintained?
- [ ] Being cross-platform?

**Comment by ralfbiedert** [comment]
My personal criteria would be all of:

- Are somewhat related to the "code-build-test" cycle (well, and code analysis, ...)
- Are (sort of) in "top-X%" of downloads, 
- Have "several 100" Github stars
- Actively maintained
- Run & compile out of the box on at least Mac, Linux, Windows 

Exceptions are ok, if there is a motivation why this is "really good" to have for the code-build-test cycle.

**Comment by kud1ing** [comment]
My feeling is to try to reduce the overlap with places like

* https://github.com/rust-unofficial/awesome-rust#build-system
* https://crates.io/keywords/cargo

and only keep the essential `clippy` and `fmt`.

**Comment by ralfbiedert** [comment]
Since we probably get quite a few people relatively new to Rust visiting the site, wouldn't it make sense to keep at least a few 'highlights', if only for discoverability of the fact that 3rd party cargo plugins exist?

**Comment by kud1ing** [comment]
I think the value of a cheat sheet lies in the quickly accessible "bare minimum" - brief explanations/insights and pointing to more detailed external information.

Instead of listing more than the bare minimum cargo plugins (and thus being in danger of entering the territory of awesome-rust) i would link to a place where they are listed, like awesome-rust or crates.io.

**Comment by ralfbiedert** [comment]
Closing for hygiene reasons. Discussion still relevant though, please comment or reopen if you have more input / other angles.
