### ISSUE TITLE
Bad pointer examples

### ISSUE THREAD

**Issue by tspiteri** [ralfbiedert/cheats.rs#7]
In the references and pointers section, `*const x` is described as an immutable raw pointer and `*mut x` is described as a mutable raw pointer. However those expressions are not valid; you wouldn't create a raw pointer to `x` using `*const x`, but using `&x as *const T` where `T` is the type of `x` (or if you like, `&x as *const _`).

**Comment by ralfbiedert** [comment]
Thanks! I removed the `*const x`, `*mut x` elements.
