### ISSUE TITLE
Unclear description of signed integer ranges

### ISSUE THREAD

**Issue by vassilibykov** [ralfbiedert/cheats.rs#73]
The footnote in the "Numeric Types" section says

> * i8, i16, ... values range from -max/2 to max/2-1, rounded to larger value.

"Larger" is unclear when used in the context of negative numbers. It may refer to the absolute value as implied here, so -128 is "larger" than -127.5, or it may be a synonym of "greater than", in which case -127 is "larger" than -127.5.

It would be more clear to say something like "values range from -max/2 to max/2, rounded toward negative infinity."

**Comment by vassilibykov** [comment]
Thanks for addressing this so quickly (and for the cheat sheet in the first place :). However, note that with the change to "toward negative infinity" the upper bound is no longer max/2 - 1, it becomes just max/2.

**Comment by ralfbiedert** [comment]
Thanks for catching, should have paid more attention :)
