### ISSUE TITLE
Suggestion: section about iteration/iterators

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#74]
https://stackoverflow.com/questions/34733811/what-is-the-difference-between-iter-and-into-iter

An "Iteration" section could give an overview over:

Tasks:
* iterate over references: [as_ref()](https://doc.rust-lang.org/std/convert/trait.AsRef.html)
* iterate over mutable references 
* iterate and consume 

Traits/methods:
* [trait Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html)
* [trait IterMut](https://doc.rust-lang.org/std/slice/struct.IterMut.html)
* producing an iterator:
  * [trait IntoIterator](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html): `into_iter()`:
    * consumes `Self`
      * use reference as in `for x in &y` if this is not desired
    * used by [`for` loop](https://doc.rust-lang.org/std/iter/index.html#for-loops-and-intoiterator)
  * `iter()` does not consume `Self`: defined for [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.iter), [Vec](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.iter)
* consuming an iterator:
  * [trait FromIterator](https://doc.rust-lang.org/std/iter/trait.FromIterator.html)
  * resuming vs non-resuming iterators

**Comment by kud1ing** [comment]
An "Iteration" section could give an overview over the tasks:
* iterate over references 
* iterate over mutable references 
* iterate and consume

**Comment by ralfbiedert** [comment]
The Iteration section is an interesting thought. 

I still have the marker traits from #63 in the back of my head, maybe those could go together (although currently I planned to place them next to data structure).  

One concern though about `iter` vs `into_iter` in particular, there are many traits with many methods, so deciding which ones to include might be hard. Why for example this one, and not also many of the other ones?

**Comment by kud1ing** [comment]
Maybe we could compress this, which gives a nice overview/introduction: https://dev.to/dandyvica/yarit-yet-another-rust-iterators-tutorial-46dk

**Comment by ralfbiedert** [comment]
The table a few pages in is really interesting and I could see us having something similar.

**Comment by kud1ing** [comment]
I liked the table at first, too. But then i thought that the "return type" column is not that interesting/helpful and when you leave that out you are left with not that much. Hm.

**Comment by kud1ing** [comment]
I think we agree that having a section about iteration is not a stupid idea.

What would you think about adding a minimal section (i suggest the main points
* `next()`
* consuming an iterator, e.g. `collect()`
* producing an iterator

and after that add/remove stuff that does not feel right?

**Comment by ralfbiedert** [comment]
This should be done. Please have a look and let me know what you think.

**Comment by kud1ing** [comment]
Not too bad. Thank you.
