### ISSUE TITLE
Suggestion: Make cheat.rs available via rustup doc

### ISSUE THREAD

**Issue by cata0309** [ralfbiedert/cheats.rs#75]
Hello !
I really like the way the books are bundled with the toolchain installed via ``rustup doc`` and I think this system can make only good to cheat.rs if decided to be included.
The ``rustup doc`` has a lot of options for different books that can be accessed offline !
      ``--alloc              The Rust core allocation and collections library``
        ``--book               The Rust Programming Language book``
        ``--cargo              The Cargo Book``
        ``--core               The Rust Core Library``
        ``--edition-guide      The Rust Edition Guide``
        ``--embedded-book      The Embedded Rust Book``
       `` --nomicon            The Dark Arts of Advanced and Unsafe Rust Programming``
        ``--reference          The Rust Reference``
       ``--rust-by-example    A collection of runnable examples that illustrate various`` 
And many other useful resources!
I know there must be a way to integrate cheat.rs with the rust lang official repository. Opening an issue on the rust repository and describing the suggestion would be a great idea. 
I suggest the ``cheats`` option to be added to ``rustup doc``.
What do you think ? 
Edit: The online version of the website ``cheat.rs`` will continue to be used.

**Comment by ralfbiedert** [comment]
I very much like the idea. Having the site being part of `rustup doc` would be amazing from a "working offline" perspective, and having a cheat sheet easily available was the reason for this site! 

Unfortunately though I doubt an unofficial documentation project will be included. However, I can file a ticket upstream and see how it goes.

**Comment by cata0309** [comment]
Please do, I don't think they will refuse you !

**Comment by cata0309** [comment]
I close this issue since I talked to the 'doc' team and their lack of organization made me be sure that the cheat.rs website will not be included in their docs in the nearly future/or just future ! Great website ! 
I found out another alternative to this, using httrack and making from time to time some updates !

**Comment by ralfbiedert** [comment]
Thanks for the update!
