### ISSUE TITLE
Suggestion: goal oriented method tables

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#76]
Basically  https://github.com/rust-lang/rust/issues/53593 which does not fit perfectly into the API documentation.

![HashMap](https://user-images.githubusercontent.com/391975/58480897-96970f00-815b-11e9-9308-6139789dca0c.png)

**Comment by ralfbiedert** [comment]
I thought a bit about this, but still have mixed feelings:

- On one hand, I would expect a Rust cheat sheet to list some of the most essential API "how to" (anecdotally, I know two people who missed `entry` and did hacky workarounds)
- On the other, this might get huge very quickly and pretty much touches what std docs should be about. Where to draw the line here?

**Comment by kud1ing** [comment]
I agree, it's tricky.

**Comment by kud1ing** [comment]
Maybe just do this for `HashMap`'s `entry()` for now, because it is special?

**Comment by ralfbiedert** [comment]
> Maybe just do this for HashMap's entry() for now, because it is special?

Just doing it for one type feels surprising to me:

- as someone coming to browse, why would I only find HashMap?
- as someone coming needing API guidance, (why) would I remember we only have HashMap?

Again, not opposed of adding it eventually, but still think this needs a better overall concept which I don't have right now :/

**Comment by ralfbiedert** [comment]
Hi, due to a lack of progress on this I'm closing this. I'm not opposed to the item, but don't know how to move this forward myself. Feel free to comment / reopen if there is new input.

(For this particular one I think the "Standard Library" section made actually some progress).
