### ISSUE TITLE
Basic types: explain `u`, `i`, `32`, `64`, `128`?

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#77]
This is about the visualizations at https://cheats.rs/#basic-types

Should we briefly explain `u`, `i`, `32`, `64`, `128` or link to the book, e.g. for people just browsing this but who are not familiar with Rust yet?

**Comment by ralfbiedert** [comment]
> Should we briefly explain u, i, 32, 64, 128 or link to the book, e.g. for people just browsing this but who are not familiar with Rust yet?

I don't mind adding a link catch-all link to the reference:

https://doc.rust-lang.org/stable/reference/types/numeric.html

However, I don't think explaining `u8` and `i32` is what this site should be about.

**Comment by kud1ing** [comment]
Fair enough, thanks.
