### ISSUE TITLE
Suggestions to improve "Custom Types" visualizatiaton

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#78]
While great overall, there are some aspects i think could be made more clearer https://cheats.rs/#custom-types

* [ ] What is the `T: !Sized` example with the arrow trying to show?
* [ ] Does the grey border take up space? In other word: has `struct S;` a size? If not: is it big?

Maybe the space within the struct (especially the padding) could be made more clearer using grey boxes within those grey borders?

I think this way we could make more clear whether the tuple `(A, B, C)` and the struct `S { a: A, b: B, c: C}` have the same size or not.

**Comment by ralfbiedert** [comment]
Feel free to post a screenshot to discuss alternative visualizations.

**Comment by kud1ing** [comment]
I wasn't sure whether the tuple or an empty stuct contain a tag or not. They seem to not include that, 
so the size of an empty stuct is 0. What would you think about including a sentence like "No tag is used, the size of an empty `struct` is 0"?

For the padding i could not come up with a good example. Would it make sense to link to https://doc.rust-lang.org/reference/type-layout.html ?

**Comment by jinmingjian** [comment]
Random insert: I submit a PR #79 for the usage of "T: !Sized" in this section. 

Then, I am reviewing the cheat sheet. Great work. 

Finally, linking to "T: ?Sized" (and other symbolic stuffs) is always a good idea.

**Comment by ralfbiedert** [comment]
@jinmingjian, thanks for the catch, got some operational blindness there!

**Comment by ralfbiedert** [comment]
I also linked to `type-layout` and `dynamically-sized-types`.

**Comment by ralfbiedert** [comment]
> What would you think about including a sentence like "No tag is used, the size of an empty struct is 0"? 

I'm not sure. the diagrams already show no tag for structs. Adding yet another statement feels very strong. If this is a really common problem I could see us adding more text, but right now I don't see that being the case.

Do you agree?

**Comment by kud1ing** [comment]
Fair enough.

**Comment by kud1ing** [comment]
Thanks.
