### ISSUE TITLE
Suggestion: add a glossary

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#83]
This allows to keep links to external resources in a single place, while also being able to add explanatory links to almost every occurences of an expression, which helps browsing visitors.

As discussed in https://github.com/ralfbiedert/cheats.rs/pull/82

Examples:
* from Wikipedia about computer graphics: https://en.wikipedia.org/wiki/Glossary_of_computer_graphics
* from the Rust book: https://doc.rust-lang.org/1.8.0/book/glossary.html
* from the Rust reference: https://doc.rust-lang.org/reference/glossary.html

**Comment by ralfbiedert** [comment]
Having a glossary with concepts used on this site sounds like a really good idea!

**Comment by kud1ing** [comment]
I am glad you like it.

**Comment by kud1ing** [comment]
In order to kickstart this, i suggest that you add a glosssary with a single entry at a place and in the form of your liking, so that people can expand on that.

If you don't have an interesting first entry candidate, i currently am interested in "associated type".

**Comment by ralfbiedert** [comment]
I never know how it should _really_ look in the end before it's almost done and usually need to iterate these things a lot, both content and design. My gut feeling is:

- It should probably go at the end of "Guides" but before "Misc"
- Each entry should be 1 line, max 2
- Overall length should be reasonable (more than few lines, less than ~1-2 pages)
- Maybe colored table style, maybe "bold keyword - description + \<br\>", whatever looks better 
- Should list concepts used already, not introduce new ones 
- Maybe (if feasible) have links in BK / EX / REF ... style to books where appropriate 

Feel free to start adding something, somewhere, and see how it looks. Once something is there I'd have to play with it as well a bit.

**Comment by ralfbiedert** [comment]
Hi, due to a lack of progress on this I'm closing this. I'm not opposed to the item, but don't know how to move this forward myself. Feel free to comment / reopen if there is new input.
