### ISSUE TITLE
Sugestion: Add subslice patterns in Pattern Matching

### ISSUE THREAD

**Issue by GrayJack** [ralfbiedert/cheats.rs#84]
Subslice pattern was recent stabilized on nightly and will come with Rust 1.42

Would be nice to have it on cheats.rs.

Making this issue now so when 1.42 comes out maybe it will be already near to completely written.

Reference: https://github.com/rust-lang/rust/pull/67712

It was a collection of RFCs, but the link has all of then for more fine detail.

**Comment by ralfbiedert** [comment]
Good idea!
