### ISSUE TITLE
Conversion table for various string types

### ISSUE THREAD

**Issue by intgr** [ralfbiedert/cheats.rs#86]
Hi. Rust has so many different string-y types. The conversions between some of them are not obvious.

I found this helpful Google sheet but currently it's not very easily discoverable. What do you think, would importing this into `cheats.rs` make sense?
https://docs.google.com/spreadsheets/d/19vSPL6z2d50JlyzwxariaYD6EU2QQUQqIDOGbiGQC7Y/edit?usp=sharing

**Comment by ralfbiedert** [comment]
I like the idea. Not sure about the design yet as the width is relatively fixed on our site. Needs probably some experimentation.

**Comment by ralfbiedert** [comment]
I have published an initial version that includes string conversions. Feedback & PRs very welcome!

**Comment by intgr** [comment]
Thanks, that's useful already. I also struggled with `Path`, `PathBuf` and `*const c_char`

**Comment by ralfbiedert** [comment]
I've added a few more, closing for now. Feel free to reopen or create new PR if you want to add other string conversions you feel are missing.
