### ISSUE TITLE
Document common attributes

### ISSUE THREAD

**Issue by ralfbiedert** [ralfbiedert/cheats.rs#89]
- [ ] must_use (and meaning where)
- [ ] derive & friends
- [ ] repr
- [ ] test
- [ ] bench
- [ ] warn/allow/ ....
- [ ] macro_export, ...
- [ ] cfg (debug assertions, feature, ...)

Should probably go into "Standard Library" section.

**Comment by patriksvensson** [comment]
Not sure if there's any documentation for `#cfg`, but that would be super nice to have together with some commonly used values such as `debug_assertions` and `feature`.

**Comment by ralfbiedert** [comment]
Great idea, added!

**Comment by ralfbiedert** [comment]
Tentatively closing. I tried this once on a branch some time ago but it didn't sit right, felt somewhat arbitrary (like if I added X, why not also add Y). Might revisit later though, more input also still welcome.
