### ISSUE TITLE
PDF should be created automatically via Github Action

### ISSUE THREAD

**Issue by ralfbiedert** [ralfbiedert/cheats.rs#91]
As discussed in #90, it would be nice if a (Docker) PDF action ran automatically and updated the releases. The ideal solution:

- Builds the page Docker-locally via Zola (preferred), or just grabs the latest released one
- Generates a portrait(?) PDF preserving background colors but w/o user visible "corner" metadata as some browsers do
- Publishes the PDF as a new release 
- Generally works without modifying the repository

**Comment by johannst** [comment]
I would take a look into this issue, if that's okay you can just assign it to me.

**Comment by ralfbiedert** [comment]
Sure, that would be great!

**Comment by johannst** [comment]
I am wondering about the trigger of this action, should it run
1. for every push event on `master`
2. or for example when a tag is created with a specific pattern

**Comment by ralfbiedert** [comment]
I think push to `master` might be easier from a workflow perspective, since the site has more of a rolling release. On the other hand, if the PDF is expensive to create we could just a tag. Your call, based on what you think works better.

**Comment by johannst** [comment]
Then let me just start to generate & release the PDF on every push to `master`.
If we find that's too much, changing the trigger afterwards is a minor change.
