### ISSUE TITLE
Add style guide?

### ISSUE THREAD

**Issue by pickfire** [ralfbiedert/cheats.rs#92]
https://doc.rust-lang.org/1.0.0/style/ it is not very discoverable, even worse that rust API guidelines I would say.

**Comment by pickfire** [comment]
I just realized that was 1.0.0.

**Comment by ralfbiedert** [comment]
Hi, thanks for the pointer. Hasn't that been superseeded by `rustfmt`? At least when i [check their repo](https://github.com/rust-lang/rust-guidelines) it says "discontinued" ...

**Comment by pickfire** [comment]
And rust-guidelines was superseeded by https://github.com/rust-dev-tools/fmt-rfcs, that looks kinda work in progress to me.
