### ISSUE TITLE
Suggestion: Extend "Behind the Scenes"

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#93]
https://users.rust-lang.org/t/when-does-rust-prefer-to-be-implicit/38636

* Sugar:
  * async/await => Future
  * for loop => `IntoIter`
* Behind the scenes:
  * Drop
  * Copy
  * Panic
  * Thread locals
  * Marker traits
  * Special traits

**Comment by kud1ing** [comment]
Ha, i've just discovered https://github.com/ralfbiedert/cheats.rs/commit/6487b3950f0b186c03ff70fabecf4e76ffdca60d

**Comment by ralfbiedert** [comment]
Random comment, last week I had a discussion with a (C++) colleague about `Copy`, move and Drop; and there was some misunderstanding around how they interact and whether / how "Rust prevents variables behind reference from being moved out".

I definitely think you're on to something there with extending that section. Just don't know yet how to pack this into a few, easily digestible lines / diagrams.

**Comment by ralfbiedert** [comment]
To add, I could imagine rehashing some fundamental concepts as one-liners as well:

- Move semantics
- Borrows
- Expression Based
- Panic Handling
