### ISSUE TITLE
String Conversions: Converting between non-UTF8 types may cause UTF8 errors

### ISSUE THREAD

**Issue by intgr** [ralfbiedert/cheats.rs#94]
The `OsString`, `CString`, `PathBuf`, `&Path` types may contain non-UTF-8 characters, but current conversion suggestions use `to_str()` which fails when it encounters a non-UTF-8 char. For example, for CString it shows:
```rust
OsString | CString::new(x.to_str()?)?
PathBuf  | CString::new(x.to_str()?)?
&Path    | x.to_str()?.into()
```

I'm not even sure what's the best way to cover these. For `Path->CString` conversion I currently use `OsStrExt`, but it's Unix-only :(
```rust
use std::os::unix::ffi::OsStrExt;
CString::new(path.as_os_str().as_bytes()).unwrap()
```
This only fails on NUL bytes, but does not do UTF-8 validation.

**Comment by intgr** [comment]
By the way, the String Conversions table is priceless, I've used it many times already.

**Comment by ralfbiedert** [comment]
Hi, thanks for the report! I've updated the table and think this this should be addressed (well, at least as good as it gets given `OsStrExt`). However, feel free to comment or reopen if you disagree!
