### ISSUE TITLE
Consider add info about rust-embedded/cross

### ISSUE THREAD

**Issue by xoac** [ralfbiedert/cheats.rs#95]
Consider provide information about [cross](https://github.com/rust-embedded/cross) in [cross compilation](https://cheats.rs/#cross-compilation) section.

**Comment by ralfbiedert** [comment]
Hi, thanks for ticket. 

I just skimmed over `cross`, but it seems to be a Linux-only 3rd-party tool, is that correct? If so, I am feeling reluctant to add it, as: 

- it will work in very specific circumstances
- we already removed utilities before #69, (there are just so many that could be added)

Is there something very special about it I'm missing?

**Comment by xoac** [comment]
I think only cross test require Linux kernel. But it  require docker for sure  (I don't know how docker works on Windows). 

It's reasonable to contains only official rust tools!
